// portfolio-data.js — single source of truth for maxjaffe.ai/lab
// Update this file when projects change. Push to GitHub → Vercel auto-deploys.
// Last updated: 2026-04-12

const PORTFOLIO = {

  platform: {
    label: "Platform ecosystem",
    supabase: "fpxardwqswlofxrupyhz",
    description: "Five interconnected apps sharing a single Supabase project, a unified agent registry, and cross-app persona system. Radar is the producer; everything else consumes from it.",
    apps: [
      {
        id: "radar",
        name: "Radar",
        url: "radar.maxjaffe.ai",
        role: "Producer",
        roleColor: "danger",
        icon: "signal",
        description: "Email intelligence hub. Polls Gmail every 15 min, classifies with 34 agents, and distributes structured data to all platform apps.",
        agents: [
          { name: "RadarOrchestrator", isOrch: true },
          { name: "EmailClassifier", isOrch: false },
          { name: "DistrictAgent", isOrch: false },
          { name: "PTAAgent", isOrch: false },
          { name: "TeacherAgent", isOrch: false },
          { name: "RecruiterAgent", isOrch: false },
          { name: "FinancialAgent", isOrch: false },
          { name: "NewsletterAgent", isOrch: false },
          { name: "FamilyFeedSync", isOrch: false },
          { name: "EmailPromotionService", isOrch: false },
          { name: "+ 24 more sub-agents", isOrch: false, isMeta: true },
        ],
        stack: ["Next.js 15", "TypeScript", "Claude API", "Gmail API", "Supabase"],
        status: "live",
      },
      {
        id: "focus-hub",
        name: "Focus Hub",
        url: "focus.maxjaffe.ai",
        role: "Consumer",
        roleColor: "info",
        icon: "target",
        description: "Personal productivity OS. Morning standup, Big 3 daily priorities, task + habit tracking, job search pipeline, self-care check-ins.",
        agents: [
          { name: "MaxOrchestrator", isOrch: true },
          { name: "FocusHubOrchestrator", isOrch: true },
          { name: "CaptureAgent", isOrch: false },
          { name: "EmailAgent", isOrch: false },
          { name: "FocusAgent", isOrch: false },
          { name: "HabitAgent", isOrch: false },
          { name: "PlanningAgent", isOrch: false },
          { name: "ReflectionAgent", isOrch: false },
          { name: "SelfCareAgent", isOrch: false },
          { name: "TaskAgent", isOrch: false },
        ],
        stack: ["Next.js 15", "TypeScript", "Claude API", "Todoist", "Supabase"],
        status: "live",
      },
      {
        id: "family-hq",
        name: "Family HQ",
        url: "family.maxjaffe.ai",
        role: "Consumer",
        roleColor: "info",
        icon: "home",
        description: "Family command center. School events, calendar, checklists, kiosk mode for kids, Recharge Menu with age-appropriate break activities.",
        agents: [
          { name: "FamilyHQOrchestrator", isOrch: true },
          { name: "CalendarAgent", isOrch: false },
          { name: "SchoolAgent", isOrch: false },
          { name: "KidsAgent", isOrch: false },
          { name: "ChecklistAgent", isOrch: false },
          { name: "RechargeMenuAgent", isOrch: false },
        ],
        stack: ["Next.js 15", "TypeScript", "Claude API", "Google Calendar", "Supabase"],
        status: "live",
      },
      {
        id: "unloader",
        name: "The Unloader",
        url: "Vercel (private)",
        role: "Consumer",
        roleColor: "success",
        icon: "brain",
        description: "Mental load management for Alex. ADHD-aware design, regulation toolkit, persona memory across sessions, dopamine break menus.",
        agents: [
          { name: "Bean", isOrch: true, subtitle: "Supporter" },
          { name: "Spark", isOrch: true, subtitle: "Challenger" },
          { name: "Echo", isOrch: true, subtitle: "Brain Dump" },
        ],
        stack: ["Next.js 15", "TypeScript", "Claude API", "Supabase"],
        status: "live",
      },
      {
        id: "profile-hub",
        name: "Profile Hub",
        url: "profiles.maxjaffe.ai",
        role: "Aggregator",
        roleColor: "warning",
        icon: "user",
        description: "Unified family profile database. SmartTagPicker with 358-interest taxonomy across 13 categories. Bidirectional sync to GiftStash via bearer token.",
        agents: [
          { name: "ProfileSyncAgent", isOrch: true },
          { name: "SmartTagPicker", isOrch: false },
          { name: "358 interests · 13 categories", isOrch: false, isMeta: true },
        ],
        stack: ["Next.js 15", "TypeScript", "Claude API", "Supabase"],
        status: "live",
      },
    ],
  },

  standalone: {
    label: "Standalone projects",
    apps: [
      {
        id: "jaffelytics",
        name: "Jaffelytics",
        url: "jaffelytics.com",
        role: "Standalone",
        roleColor: "amber",
        icon: "chart",
        description: "Premium SEO audit + lead pipeline platform for SMB clients. Full prospect-to-outreach pipeline with 7 autonomous agents.",
        supabase: "skrpyjghjxfktmqylkzr",
        agents: [
          { name: "Orchestrator", isOrch: true },
          { name: "ProspectFinder", isOrch: false },
          { name: "LeadQA", isOrch: false },
          { name: "SEOAudit", isOrch: false },
          { name: "6 HTTP adapters", isOrch: false, isMeta: true },
          { name: "ScoringAgent", isOrch: false },
          { name: "ContactEnrichment", isOrch: false },
          { name: "OutreachDraft", isOrch: false },
        ],
        pipeline: [
          { name: "ProspectFinder", desc: "Discovers SMB leads matching ICP" },
          { name: "LeadQA", desc: "Validates & deduplicates" },
          { name: "SEOAudit", desc: "6 HTTP adapters in parallel" },
          { name: "ScoringAgent", desc: "fit_score 0–100 + rationale" },
          { name: "ContactEnrichment", desc: "Finds decision-maker email" },
          { name: "OutreachDraft", desc: "Personalised subject + body" },
        ],
        icp: [
          { score: "≥ 75 + email", label: "Auto-qualify", tier: "green" },
          { score: "60 – 74", label: "Flag for review", tier: "amber" },
          { score: "< 60", label: "Below threshold", tier: "gray" },
        ],
        stack: ["Next.js 16", "TypeScript", "Tailwind 4", "Claude API", "Supabase", "Vercel"],
        status: "live",
      },
      {
        id: "giftstash",
        name: "GiftStash",
        url: "giftstash.app",
        role: "Standalone",
        roleColor: "amber",
        icon: "gift",
        description: "SMS-first gift tracking. Auto-detects persona from message style. Twilio A2P registered.",
        agents: [
          { name: "Dash", isOrch: true, subtitle: "Quick gifter" },
          { name: "Scout", isOrch: true, subtitle: "Researcher" },
          { name: "GiftEnrichmentPipeline", isOrch: false },
          { name: "TrendingGiftsAgent", isOrch: false },
        ],
        stack: ["Next.js", "TypeScript", "Claude API", "Twilio", "Supabase"],
        status: "live",
      },
      {
        id: "community-voice",
        name: "Community Voice",
        url: "No-code pipeline",
        role: "No-code",
        roleColor: "teal",
        icon: "megaphone",
        description: "Research-backed D&I content pipeline for local Facebook groups. 45-seed database of peer-reviewed research. Human-in-the-loop approval before posting.",
        agents: [
          { name: "Selector", isOrch: true },
          { name: "Writer", isOrch: true },
          { name: "QA Reviewer", isOrch: true },
          { name: "Human-in-the-loop", isOrch: false, isMeta: true },
        ],
        stack: ["Claude API", "Google Sheets", "Manual approval"],
        status: "active",
      },
      {
        id: "study-buddy",
        name: "Study Buddy",
        url: "Vercel",
        role: "Standalone",
        roleColor: "amber",
        icon: "book",
        description: "Photo-to-flashcard generator for the kids. Point camera at any textbook page — Claude extracts and formats flashcards. Deepgram TTS reads them back.",
        agents: [
          { name: "SessionOrchestrator", isOrch: true },
          { name: "FlashcardAgent", isOrch: false },
        ],
        stack: ["Next.js", "TypeScript", "Claude API", "Deepgram", "Supabase"],
        status: "live",
      },
    ],
  },

  flows: [
    { from: "Gmail", to: "Radar", label: "polls every 15 min" },
    { from: "Radar", to: "Focus Hub", label: "radar_family_feed · email insights" },
    { from: "Radar", to: "Family HQ", label: "radar_family_feed · family events" },
    { from: "Radar", to: "The Unloader", label: "unified_tasks · unified_reminders" },
    { from: "Radar", to: "Profile Hub", label: "POST /api/enrich · bearer token" },
    { from: "Family HQ", to: "The Unloader", label: "cached_calendar_events" },
    { from: "Focus Hub", to: "Radar", label: "Gmail proxy · all email ops" },
    { from: "Profile Hub", to: "GiftStash", label: "syncToGiftStashAsync · bearer token", bidirectional: true },
  ],

  sharedDb: {
    id: "fpxardwqswlofxrupyhz",
    tables: [
      { name: "radar_family_feed", owner: "Radar → Family HQ, Focus Hub, Unloader" },
      { name: "unified_tasks", owner: "Radar → Unloader, Focus Hub" },
      { name: "unified_reminders", owner: "Radar → Unloader" },
      { name: "cached_calendar_events", owner: "Family HQ → Unloader, Focus Hub" },
      { name: "family_members", owner: "Family HQ → Profile Hub, Radar" },
      { name: "platform_chat_history", owner: "All apps" },
      { name: "unified_profiles", owner: "Profile Hub" },
      { name: "agent_registry", owner: "Radar Observatory" },
      { name: "agent_analytics", owner: "Radar Observatory" },
    ],
  },

};
